/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWonRouteImport } from './routes/_app.won'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOutreachRouteImport } from './routes/_app.outreach'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNotInterestedRouteImport } from './routes/_app.not-interested'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppManualLeadsRouteImport } from './routes/_app.manual-leads'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppInterestedRouteImport } from './routes/_app.interested'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppFollowupsRouteImport } from './routes/_app.followups'
import { Route as AppDiscoveryRouteImport } from './routes/_app.discovery'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppBrainRouteImport } from './routes/_app.brain'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWonRoute = AppWonRouteImport.update({
  id: '/won',
  path: '/won',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotInterestedRoute = AppNotInterestedRouteImport.update({
  id: '/not-interested',
  path: '/not-interested',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppManualLeadsRoute = AppManualLeadsRouteImport.update({
  id: '/manual-leads',
  path: '/manual-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInterestedRoute = AppInterestedRouteImport.update({
  id: '/interested',
  path: '/interested',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowupsRoute = AppFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/billing': typeof AppBillingRoute
  '/brain': typeof AppBrainRoute
  '/conversations': typeof AppConversationsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/followups': typeof AppFollowupsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/interested': typeof AppInterestedRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/manual-leads': typeof AppManualLeadsRoute
  '/meetings': typeof AppMeetingsRoute
  '/memory': typeof AppMemoryRoute
  '/not-interested': typeof AppNotInterestedRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/outreach': typeof AppOutreachRoute
  '/profile': typeof AppProfileRoute
  '/won': typeof AppWonRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/billing': typeof AppBillingRoute
  '/brain': typeof AppBrainRoute
  '/conversations': typeof AppConversationsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/followups': typeof AppFollowupsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/interested': typeof AppInterestedRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/manual-leads': typeof AppManualLeadsRoute
  '/meetings': typeof AppMeetingsRoute
  '/memory': typeof AppMemoryRoute
  '/not-interested': typeof AppNotInterestedRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/outreach': typeof AppOutreachRoute
  '/profile': typeof AppProfileRoute
  '/won': typeof AppWonRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/brain': typeof AppBrainRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/discovery': typeof AppDiscoveryRoute
  '/_app/followups': typeof AppFollowupsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/interested': typeof AppInterestedRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/manual-leads': typeof AppManualLeadsRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/not-interested': typeof AppNotInterestedRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/outreach': typeof AppOutreachRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/won': typeof AppWonRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/billing'
    | '/brain'
    | '/conversations'
    | '/discovery'
    | '/followups'
    | '/integrations'
    | '/interested'
    | '/knowledge'
    | '/manual-leads'
    | '/meetings'
    | '/memory'
    | '/not-interested'
    | '/notifications'
    | '/onboarding'
    | '/outreach'
    | '/profile'
    | '/won'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analytics'
    | '/billing'
    | '/brain'
    | '/conversations'
    | '/discovery'
    | '/followups'
    | '/integrations'
    | '/interested'
    | '/knowledge'
    | '/manual-leads'
    | '/meetings'
    | '/memory'
    | '/not-interested'
    | '/notifications'
    | '/onboarding'
    | '/outreach'
    | '/profile'
    | '/won'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/analytics'
    | '/_app/billing'
    | '/_app/brain'
    | '/_app/conversations'
    | '/_app/discovery'
    | '/_app/followups'
    | '/_app/integrations'
    | '/_app/interested'
    | '/_app/knowledge'
    | '/_app/manual-leads'
    | '/_app/meetings'
    | '/_app/memory'
    | '/_app/not-interested'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/outreach'
    | '/_app/profile'
    | '/_app/won'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/won': {
      id: '/_app/won'
      path: '/won'
      fullPath: '/won'
      preLoaderRoute: typeof AppWonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach': {
      id: '/_app/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/not-interested': {
      id: '/_app/not-interested'
      path: '/not-interested'
      fullPath: '/not-interested'
      preLoaderRoute: typeof AppNotInterestedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manual-leads': {
      id: '/_app/manual-leads'
      path: '/manual-leads'
      fullPath: '/manual-leads'
      preLoaderRoute: typeof AppManualLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interested': {
      id: '/_app/interested'
      path: '/interested'
      fullPath: '/interested'
      preLoaderRoute: typeof AppInterestedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/followups': {
      id: '/_app/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AppFollowupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery': {
      id: '/_app/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain': {
      id: '/_app/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBrainRoute: typeof AppBrainRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppFollowupsRoute: typeof AppFollowupsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInterestedRoute: typeof AppInterestedRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppManualLeadsRoute: typeof AppManualLeadsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppNotInterestedRoute: typeof AppNotInterestedRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOutreachRoute: typeof AppOutreachRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWonRoute: typeof AppWonRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBrainRoute: AppBrainRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppFollowupsRoute: AppFollowupsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInterestedRoute: AppInterestedRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppManualLeadsRoute: AppManualLeadsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppNotInterestedRoute: AppNotInterestedRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOutreachRoute: AppOutreachRoute,
  AppProfileRoute: AppProfileRoute,
  AppWonRoute: AppWonRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
