/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppOutreachRouteImport } from './routes/_app.outreach'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppDiscoveryRouteImport } from './routes/_app.discovery'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppBrainRouteImport } from './routes/_app.brain'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/brain': typeof AppBrainRoute
  '/conversations': typeof AppConversationsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/meetings': typeof AppMeetingsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/outreach': typeof AppOutreachRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/brain': typeof AppBrainRoute
  '/conversations': typeof AppConversationsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/meetings': typeof AppMeetingsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/outreach': typeof AppOutreachRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/brain': typeof AppBrainRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/discovery': typeof AppDiscoveryRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/outreach': typeof AppOutreachRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/brain'
    | '/conversations'
    | '/discovery'
    | '/knowledge'
    | '/meetings'
    | '/onboarding'
    | '/outreach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/brain'
    | '/conversations'
    | '/discovery'
    | '/knowledge'
    | '/meetings'
    | '/onboarding'
    | '/outreach'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/brain'
    | '/_app/conversations'
    | '/_app/discovery'
    | '/_app/knowledge'
    | '/_app/meetings'
    | '/_app/onboarding'
    | '/_app/outreach'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach': {
      id: '/_app/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery': {
      id: '/_app/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain': {
      id: '/_app/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBrainRoute: typeof AppBrainRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOutreachRoute: typeof AppOutreachRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBrainRoute: AppBrainRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOutreachRoute: AppOutreachRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
